change release workflow

diff --git a/.github/workflows/github-actions-release.yml b/.github/workflows/github-actions-release.yml
--- a/.github/workflows/github-actions-release.yml
+++ b/.github/workflows/github-actions-release.yml
@@ -67,9 +67,9 @@ jobs:
       - name: Get latest tag
         id: get_tag
         run: |
-          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
+          latest_tag=$(git tag | sort -V | tail -n 1)
           if [ -z "$latest_tag" ]; then
-            latest_tag="v0.0.0"
+          latest_tag="v0.0.0"
           fi
           echo "Latest tag: $latest_tag"
           echo "::set-output name=latest_tag::$latest_tag"
@@ -102,10 +102,10 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  release-main:
+  release:
     runs-on: ubuntu-latest
     needs: [ test ]
-    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
+    if: github.event_name == 'workflow_dispatch'
 
     steps:
       - name: Checkout code
@@ -126,34 +126,53 @@ jobs:
         run: |
           latest_tag=${{ steps.get_tag.outputs.latest_tag }}
           release_type=${{ github.event.inputs.release_type }}
-          if [ "$release_type" == "major" ]; then
-            if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-              major=$((BASH_REMATCH[1] + 1))
-              new_tag="v${major}.0.0"
-            else
-              new_tag="v1.0.0"
-            fi
-          elif [ "$release_type" == "minor" ]; then
-            if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
-            major=${BASH_REMATCH[1]}
-            minor=$((BASH_REMATCH[2] + 1))
-            new_tag="v${major}.${minor}.0"
-            else
-            new_tag="v1.1.0"
-            fi
-          elif [ "$release_type" == "patch" ]; then
-            if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+          branch=${{ steps.vars.outputs.branch }}
+          
+          if [[ "$branch" == "develop" ]]; then
             major=${BASH_REMATCH[1]}
             minor=${BASH_REMATCH[2]}
-            patch=$((BASH_REMATCH[3] + 1))
-            new_tag="v${major}.${minor}.${patch}"
+            patch=${BASH_REMATCH[3]}
+            beta=${BASH_REMATCH[4]}
+            if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)-beta\.([0-9]+)$ ]]; then
+              new_tag="v${major}.${minor}.${patch}-beta.$((beta + 1))"
+            elif [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+              new_tag="v${major}.${minor}.${patch+1}-beta.1"
             else
-            new_tag="v1.0.1"
+              new_tag="v0.0.0-beta.1"
+            fi
+          elif [[ "$branch" == "main" ]]; then
+            if [ "$release_type" == "major" ]; then
+              if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+                major=$((BASH_REMATCH[1] + 1))
+                new_tag="v${major}.0.0"
+              else
+                new_tag="v0.0.0"
+              fi
+            elif [ "$release_type" == "minor" ]; then
+              if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+                major=${BASH_REMATCH[1]}
+                minor=$((BASH_REMATCH[2] + 1))
+                new_tag="v${major}.${minor}.0"
+              else
+                new_tag="v0.0.0"
+              fi
+            elif [ "$release_type" == "patch" ]; then
+              if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
+                major=${BASH_REMATCH[1]}
+                minor=${BASH_REMATCH[2]}
+                patch=$((BASH_REMATCH[3] + 1))
+                new_tag="v${major}.${minor}.${patch}"
+              else
+                new_tag="v0.0.0"
+              fi
+            else
+              echo "Invalid release type specified."
+              exit 1
             fi
           else
-            echo "Invalid release type specified."
+            echo "No valid branch or tag type specified."
             exit 1
-            fi
+          fi
           
           echo "New tag: $new_tag"
           echo "::set-output name=new_tag::$new_tag"
